//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XKPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPAT_OUT_EMR
    {
        public int EMR_REC_ID { get; set; }
        public string PATIENT_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string PATIENT_NAME { get; set; }
        public Nullable<System.DateTime> VISIT_DATE { get; set; }
        public string COMPLAINTS { get; set; }
        public string CASE_ALLERGY { get; set; }
        public string CASE_NOW { get; set; }
        public string CASE_OLD { get; set; }
        public Nullable<int> FIRST_VISIT_FLAG { get; set; }
        public string PHYSICAL { get; set; }
        public string CHECK_ITEM_NAME { get; set; }
        public string CHECK_RESULT { get; set; }
        public string DIAGNOSIS_CODE { get; set; }
        public string DIAGNOSIS_NAME { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
