//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPAT_CHECK_RECORD
    {
        public int CHECK_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string PATIENT_ID { get; set; }
        public string MO_CHECK_NO { get; set; }
        public string APPLY_NO { get; set; }
        public Nullable<int> SYSTEM_CODE { get; set; }
        public string CHECK_TYPE { get; set; }
        public string CHECK_ITEM_CODE { get; set; }
        public string CHECK_ITEM_NAME { get; set; }
        public Nullable<System.DateTime> APPLY_DATE { get; set; }
        public string APPLY_DEPT_CODE { get; set; }
        public string APPLY_DEPT_NAME { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string EXEC_DEPT_CODE { get; set; }
        public string EXEC_DEPT_NAME { get; set; }
        public string BODY_PART_NAME { get; set; }
        public string CHECK_RESULT_TYPE { get; set; }
        public string REPORT_OBJECTIVE { get; set; }
        public string REPORT_SUBJECTIVE { get; set; }
        public string REPORT_RESULT { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string REPORT_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
