//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPAT_TEST_RECORD
    {
        public string SAMPLE_NO { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string PATIENT_ID { get; set; }
        public string MO_TEST_NO { get; set; }
        public string APPLY_NO { get; set; }
        public string TEST_ITEM_CODE { get; set; }
        public string TEST_ITEM_NAME { get; set; }
        public string SAMPLE_TYPE_CODE { get; set; }
        public string SAMPLE_TYPE_NAME { get; set; }
        public string SAMPLE_BODY { get; set; }
        public string APPLY_DEP_CODE { get; set; }
        public string APPLY_DEP_NAME { get; set; }
        public Nullable<System.DateTime> APPLY_DATE { get; set; }
        public Nullable<System.DateTime> SAMPLING_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> TEST_DATE { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string REPORT_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
