//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XKPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPAT_PATHOLOGY_RECORD
    {
        public int PATHOLOGY_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string PATIENT_ID { get; set; }
        public string PATIENT_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<int> GENDER_CODE { get; set; }
        public string CASE_NO { get; set; }
        public string MO_CHECK_NO { get; set; }
        public string COMPLAINTS { get; set; }
        public string DIAGNOSE_NAME { get; set; }
        public string MEDICAL_HISTORY { get; set; }
        public string APPLY_NO { get; set; }
        public Nullable<System.DateTime> APPLY_DATE { get; set; }
        public string APPLY_DEPT_CODE { get; set; }
        public string APPLY_DEPT_NAME { get; set; }
        public string APPLY_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> SAMPLING_DATE { get; set; }
        public string SAMPLE_PART { get; set; }
        public string SAMPLE_TYPE_NAME { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string CHECK_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string REPORT_OBJECTIVE { get; set; }
        public string REPORT_SUBJECTIVE { get; set; }
        public string REPORT_RESULT { get; set; }
        public string BIOPSY { get; set; }
        public string PATHOLOGY { get; set; }
        public string POSITIVE { get; set; }
        public string SECTION_COUNT { get; set; }
        public string FROZEN_RESULT { get; set; }
        public Nullable<System.DateTime> FROZEN_REPORT_DATE { get; set; }
        public Nullable<System.DateTime> REPORT_DATE_TIME { get; set; }
        public string REPORT_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
