//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_PROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TC_PROJECT()
        {
            this.TC_SD_INFO = new HashSet<TC_SD_INFO>();
        }
    
        public int ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UDP_USER_ID { get; set; }
        public string CDR_IP { get; set; }
        public string CDR_USER_NAME { get; set; }
        public string CDR_PWD { get; set; }
        public string SDRIP { get; set; }
        public string SDR_USER_NAME { get; set; }
        public string SDR_PWD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_SD_INFO> TC_SD_INFO { get; set; }
    }
}
