//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_SD_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TC_SD_INFO()
        {
            this.TC_IN_GROUP_SETTING = new HashSet<TC_IN_GROUP_SETTING>();
            this.TC_DATAITEM_SETTING = new HashSet<TC_DATAITEM_SETTING>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
        public string SD_CODE { get; set; }
        public string SD_NAME { get; set; }
        public Nullable<int> IN_GROUP_NUM { get; set; }
        public Nullable<int> DATAITEM_NUM { get; set; }
        public Nullable<int> CAL_KPI_NUM { get; set; }
        public Nullable<System.DateTime> UDP_DATE { get; set; }
        public string UDP_USER_ID { get; set; }
    
        public virtual TC_PROJECT TC_PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_IN_GROUP_SETTING> TC_IN_GROUP_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_DATAITEM_SETTING> TC_DATAITEM_SETTING { get; set; }
    }
}
